title: Sell Digital Products with Filemonk
author: Filemonk
email: support@filemonk.io
description: >
  Sell digital products, send digital files and downloads.
baseurl: ''
url: 'filemonk.io'
header_pages:
  - index.md
  - help.md
footer_links:
  privacy:
    link: /policy.html
    title: Privacy Policy
  terms:
    link: /terms.html
    title: Terms & Conditions
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
theme: minima
plugins:
    - jekyll-seo-tag
